### ISSUE TITLE
 ‘showToolbar’ was not declared in this scope

### ISSUE THREAD

**Issue by kuh3h3** [nomacs/nomacs-plugins#18]
build failed on recent git nomacs.

[ 83%] Building CXX object plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/src/DkImgTransformationsPlugin.cpp.o
/home/kuh3h3/nomacs/ImageLounge/plugins/AffineTransformations/src/DkImgTransformationsPlugin.cpp: In member function ‘virtual void nmp::DkImgTransformationsViewPort::setVisible(bool)’:
/home/kuh3h3/nomacs/ImageLounge/plugins/AffineTransformations/src/DkImgTransformationsPlugin.cpp:743:84: error: ‘showToolbar’ was not declared in this scope
  if (imgTransformationsToolbar) emit showToolbar(imgTransformationsToolbar, visible);
                                                                                    ^
plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/build.make:70: 'plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/src/DkImgTransformationsPlugin.cpp.o' 타겟에 대한 명령이 실패했습니다
make[2]: *** [plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/src/DkImgTransformationsPlugin.cpp.o] error 1
CMakeFiles/Makefile2:374: 'plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/all' 타겟에 대한 명령이 실패했습니다
make[1]: *** [plugins/AffineTransformations/CMakeFiles/affineTransformPlugin.dir/all] error 2
Makefile:151: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] error 2

**Comment by diemmarkus** [comment]
fixed - thx!

**Comment by dvzrv** [comment]
@diemmarkus as this is yet unreleased I'm also affected by this when packaging nomacs for Arch Linux in version 3.14. Please tag a new release!

**Comment by diemmarkus** [comment]
sorry, I forgot that... -> done
