### ISSUE TITLE
invalid syntax in CMake files

### ISSUE THREAD

**Issue by rindeal** [nomacs/nomacs-plugins#19]
They contain `$(CONFIGURATION)` which is not a CMake variable since it's not using curly braces.

Example: https://github.com/nomacs/nomacs-plugins/blob/c7a5de46ce2a0751d8b358c68414831964920e59/PatchMatchingPlugin/CMakeLists.txt#L51

This makes the build fail using ninja backend since ninja is unable to parse the generated `ninja.build` file. Ninja spits out an error message like this:

```
ninja: error: build.ninja:845: bad $-escape (literal $ must be written as $$)
```

**Comment by diemmarkus** [comment]
Hi,

`$(CONFIGURATION)` is a VisualStudio variable... so to actually fix this we could add an `if (MSVC)` branch. NOTE: this plugin should not be added to everyday nomacs installations (it's rather a 'scientific' plugin).

cheers,
markus

**Comment by rindeal** [comment]
It's not just this plugin, it's currently spread across all 11 plugins.
