### ISSUE TITLE
[OcrPlugin] Tesseract Dialogs

### ISSUE THREAD

**Issue by dschoerk** [nomacs/nomacs-plugins#23]
Tesseract creates a dialog window in some cases. (E.g. when the file for a chosen language is missing). Might lead to problems while using batch processing. Solution: Check if the required files are available before starting the batch processing.

**Comment by diemmarkus** [comment]
I have now added viewport messages...

**Comment by dschoerk** [comment]
my bad, thought that was a message box created inside tesseract. was actually a QMessageBox create by myself and is removed by now already. 

fixed in https://github.com/nomacs/nomacs-plugins/commit/9300fcaa2ff01100e40df29349f0c0ac37c1e11b
