### ISSUE TITLE
Add plugin as flatpak extension for nomacs flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs-plugins#29]
Hi. This just a reminder for this work which it will come in future.

Best.

**Comment by Nokia808** [comment]
Is there any progression regarding this issue ?

**Comment by diemmarkus** [comment]
nope - I will let you know as soon as there are good news here... 
currently I'm automating the windows packaging

**Comment by Nokia808** [comment]
@diemmarkus 
The plug-ins received. I test only the paint plug-in & it working. I think we should close this, & if any error existing then should treated in new issue.

Thank you for this nice work !
