### ISSUE TITLE
Utilizing "nomacs" as a frontend for "unpaper" to optoimize image(s)

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs-plugins#30]
Hi.
There is a very strong command line library that could be used for optimizing image(s) as following:

- descreen (remove black dots)
- deskew (correct slope)
- enhance contents (text)
- remove black margins
- centralized (make contents within middle of image)
- split image vertically at mid-line

We have a project called "ScanTailer Advanced" do most those except "centralized" & it use other library not unpaper ...

I would like to suggest to make nomacs as a frontend for unpaper by utilizing unpaper as plugin to nomacs. 

If you find this idea good, then please make it multithreaded so that nomacs will never crashed & crashing system with it if processing larg number of images at one (in batch mode). I mean when program finish process of one image, then should close it & go no next image instead [[maintain images opened after finish their processing, an approach used by Gscan2pdf - a frontend for unpaper - which make it crash & crashing system when used to process large number of images]].

Please feel free to close this request if you find it not suitable for nomacs ....

Thank you.

**Comment by diemmarkus** [comment]
yes, sure! If you have any questions how to create a batch plugin - please don't hesitate to ask here...

> make it multithreaded so that nomacs will never crashed & crashing system with it if processing larg number of images at one (in batch mode).

can you elaborate on that? nomacs batch processing is multi-threaded & it *should* of course never crash.

**Comment by Nokia808** [comment]
@diemmarkus 
Dear unfortunately I'm not programmer & have no facilities to learn programming ...

I forgot in my 1st post to give sites of unpaper. Bellow their sites & documentation:
https://www.flameeyes.com/projects/unpaper
https://github.com/unpaper/unpaper

However, I'm starting to think that this issue is not suitable because ScanTailor Advanced in  nearly complete & I review the input file format that supported by unpaper & indeed they are only .tiff & pnm family - see:
https://github.com/unpaper/unpaper/blob/master/doc/file-formats.md

So, I will close this issue ...
