### ISSUE TITLE
Unable to build with nomacs 3.15.0 and qt >= 5.15.0

### ISSUE THREAD

**Issue by dvzrv** [nomacs/nomacs-plugins#32]
Hi! I'm currently trying to build nomacs including the nomacs-plugins.
Unfortunately this doesn't work because the multiple fixes for many of the plugins have been applied on top of 3.14.0 but these patches can not be cherry-picked or applied cleanly on top of 3.14.0.
Please tag a new version, so that building of nomacs 3.15.0 + plugins can be done.

Thanks!

**Comment by diemmarkus** [comment]
I have created a pre-release for [v3.15](https://github.com/nomacs/nomacs-plugins/releases/tag/3.15.1616) - I hope that works for you. The official release (v3.16) will follow as soon as flathub is working properly.
