### ISSUE TITLE
Adding text to image by "Paint to Image" plug-ins not support system fonts (changing the font of text)

### ISSUE THREAD

**Issue by Nokia808** [nomacs/nomacs-plugins#36]
Hi. As the title saying ...

I'm installed nomacs as flatpak from FlatHub ...

**Comment by diemmarkus** [comment]
I think we won't add changing fonts: with the paint plugin you can currently annotate stuff in an image (plain and simple). I would recommend using another software (i.e. gimp, photoshop) if you are looking for artistic image edits...

**Comment by Nokia808** [comment]
@diemmarkus 
Hi. Please re-consider your decision ! Implementing this feature not difficult, as I think, because it is already implemented in ksnip & working very okay even from flatpak version of ksnip !

All what you need is to import it from code of ksnip. Kindly, look for it's code:
https://github.com/ksnip/ksnip 

If you import from codes of ksnip built-in editor, you will improve your plug-ins to great degree ....

**Comment by Nokia808** [comment]
@diemmarkus 
Look for this screenshot for settings of ksnip editor (annotator):

![ksnip-setting](https://user-images.githubusercontent.com/25375330/89213509-ba9e7d80-d5b4-11ea-9d8e-54d1355425ac.png)

It is just small step - not huge - to make nomacs more convenient than GIMP. I know GIMP & used it but it is difficult ..... Your program very easy & for that very convenient .....

**Comment by diemmarkus** [comment]
> If you import from codes of ksnip built-in editor, you will improve your plug-ins to great degree ....

I think we currently have more pressing issues/features than changing fonts in the paint plugin (I am working on a new crop tool [#345](https://github.com/nomacs/nomacs/issues/345)). 
a general remark: even if licenses allow it, it is in general not possible to just copy&paste or import code from other projects.
